spring:
  application:
    name: SpacePay Savings App
  datasource:
    url: jdbc:postgresql://localhost:5432/spaze_pay_savings_db
    username: ndifrekealexander
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    sender: info@spazepay.com
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: false

logging:
  level:
    root: INFO
    com.spazepay: DEBUG
    org:
      springframework:
        scheduling:
          annotation:
            ScheduledAnnotationBeanPostProcessor: DEBUG
          support:
            TaskUtils$LoggingErrorHandler: DEBUG
  file:
    name: logs/spazepay-app.log

jwt:
  secret: QW5vdGhlclNlY3JldEtleUZvckpXVC0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==

app:
  default:
    currency: NGN