spring:
  application:
    name: SpacePay Savings App
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.spazepay: DEBUG
    org:
      springframework:
        scheduling:
          annotation:
            ScheduledAnnotationBeanPostProcessor: DEBUG
          support:
            TaskUtils$LoggingErrorHandler: DEBUG
  file:
    name: logs/spazepay-app.log

jwt:
  secret: QW5vdGhlclNlY3JldEtleUZvckpXVC0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==

app:
  default:
    currency: NGN