spring:
  datasource:
    url: jdbc:postgresql://spaze-pay-savings-db.cuzi4kaqijcy.us-east-1.rds.amazonaws.com:5432/spaze_pay_savings_db
    username: spazepayadmin
    password: SecureProdPass123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIA57GKFUL3Y4BJH5D6
    password: BL0ZLxoLlFuDdwPfIfW+YCvNE88AdWw6NtslL8pBwhhZ
    sender: spazepay@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    root: INFO
    com.spazepay: DEBUG
    org:
      springframework:
        scheduling:
          annotation:
            ScheduledAnnotationBeanPostProcessor: DEBUG
          support:
            TaskUtils$LoggingErrorHandler: DEBUG
  file:
    name: logs/spazepay-app.log

jwt:
  secret: QW5vdGhlclNlY3JldEtleUZvckpXVC0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==

app:
  default:
    currency: NGN